export const menuItems = [
  {
    title: "Home",
    alt: "home icon",
    src: "/home.svg",
    href: "/home",
  },
  {
    title: "Users",
    alt: "users icon",
    src: "/users.svg",
    href: "/users",
  },
  {
    title: "Designations",
    alt: "designations icon",
    src: "/designations.svg",
    href: "/designations",
  },
  {
    title: "Locations",
    alt: "locations icon",
    src: "/locations.svg",
    href: "/locations",
  },
  {
    title: "Courses",
    alt: "courses icon",
    src: "/courses.svg",
    href: "/courses",
  },
  {
    title: "Semesters",
    alt: "semesters icon",
    src: "/semesters.svg",
    href: "/semesters",
  },
  {
    title: "Faculties",
    alt: "faculties icon",
    src: "/faculties.svg",
    href: "/faculties",
  },
  {
    title: "Sections",
    alt: "sections icon",
    src: "/sections.svg",
    href: "/sectioncoordinator",
  },
  {
    title: "Exam Strength",
    alt: "examstrength icon",
    src: "/examstrength.svg",
    href: "/ecws",
  },
  {
    title: "Exam Questions",
    alt: "examquestions icon",
    src: "/examquestions.svg",
    href: "/examquestions",
  },
  {
    title: "Daily QB Status",
    alt: "dailyqb icon",
    src: "/dailyqb.svg",
    href: "/dailyQbStatus",
  },
  {
    title: "API Test",
    alt: "api icon",
    src: "/home.svg",
    href: "/testapi",
  },
  {
    title: "Sections Test",
    alt: "sections test icon",
    src: "/sections.svg",
    href: "/sectionstest",
  },
];
